In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import keras
from keras.models import Sequential
from keras.layers import Dense

import warnings
warnings.filterwarnings('ignore')

Using TensorFlow backend.
/home/shashankmoghe/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/shashankmoghe/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/shashankmoghe/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/shashankmoghe/.local/lib/python3.7/sit

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
dataset.set_index('RowNumber')

CustomerId    Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                      
1            15634602   Hargrave          619    France  Female   42       2   
2            15647311       Hill          608     Spain  Female   41       1   
3            15619304       Onio          502    France  Female   42       8   
4            15701354       Boni          699    France  Female   39       1   
5            15737888   Mitchell          850     Spain  Female   43       2   
...               ...        ...          ...       ...     ...  ...     ...   
9996         15606229   Obijiaku          771    France    Male   39       5   
9997         15569892  Johnstone          516    France    Male   35      10   
9998         15584532        Liu          709    France  Female   36       7   
9999         15682355  Sabbatini          772   Germany    Male   42       3   
10000        15628319     Walker          792    France  Female   28       4   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   
...              ...            ...        ...             ...   
9996            0.00              2          1               0   
9997        57369.61              1          1               1   
9998            0.00              1          0               1   
9999        75075.31              2          1               0   
10000      130142.79              1          1               0   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0  
...                    ...     ...  
9996              96270.64       0  
9997             101699.77       0  
9998              42085.58       1  
9999              92888.52       1  
10000             38190.78       0  

[10000 rows x 13 columns]

In [4]:
print(np.unique(X[:, 1]))
print(np.unique(X[:, 2]))

['France' 'Germany' 'Spain']
['Female' 'Male']


In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
Xsample = X

In [7]:
X = Xsample

In [8]:
X[1], X.shape, Xsample[1], Xsample.shape

(array([608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       dtype=object),
 (10000, 10),
 array([608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       dtype=object),
 (10000, 10))

In [9]:
labelencoder = LabelEncoder()
X[:, 1] = labelencoder.fit_transform(X[:, 1])
X[:, 2] = labelencoder.fit_transform(X[:, 2])

In [22]:
X[1], X.shape, Xsample[1], Xsample.shape

(array([608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58], dtype=object),
 (10000, 10),
 array([608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58], dtype=object),
 (10000, 10))

In [ ]:
X[1], X.shape, Xsample[1], Xsample.shape

In [ ]:
X[1], X.shape, Xsample[1], Xsample.shape

In [ ]:
X[1], X.shape, Xsample[1], Xsample.shape

In [1]:
import pickle
def load_from_pickle():
    pickle_in = open('X.pickle', 'rb')
    X = pickle.load(pickle_in)
    pickle_in.close()
    
    pickle_in = open('Y.pickle', 'rb')
    y = pickle.load(pickle_in)
    pickle_in.close()
    
    return X, y

In [2]:
X, y = load_from_pickle()

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
X_train[1], X_train.shape, X[1], X.shape

(array([-0.91601335,  0.91601335, -1.01460667,  1.75486502, -0.57369368,
        -2.30455945,  0.30102557, -1.37744033, -0.00631193, -0.92159124,
         0.64259497,  0.9687384 , -0.74866447]),
 (8000, 13),
 array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 6.0800000e+02, 4.1000000e+01, 1.0000000e+00,
        8.3807860e+04, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.1254258e+05]),
 (10000, 13))

In [8]:
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 50, init = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 50, init = 'uniform', activation = 'relu'))

# Adding the third hidden layer
classifier.add(Dense(output_dim = 50, init = 'uniform', activation = 'relu'))

# Adding the fourth hidden layer
classifier.add(Dense(output_dim = 50, init = 'uniform', activation = 'relu'))

# Adding the fifth hidden layer
classifier.add(Dense(output_dim = 50, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 50)

# Part 3 - Making the predictions and evaluating the model

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/50
8000/8000 [==============================] - 2s 189us/step - loss: 0.4429 - accuracy: 0.8066
Epoch 2/50
8000/8000 [==============================] - 1s 155us/step - loss: 0.3751 - accuracy: 0.8429
Epoch 3/50
8000/8000 [==============================] - 1s 153us/step - loss: 0.3529 - accuracy: 0.8536
Epoch 4/50
8000/8000 [==============================] - 1s 151us/step - loss: 0.3492 - accuracy: 0.8559
Epoch 5/50
8000/8000 [==============================] - 1s 151us/step - loss: 0.3457 - accuracy: 0.8605
Epoch 6/50
8000/8000 [==============================] - 1s 156us/step - loss: 0.3447 - accuracy: 0.8587
Epoch 7/50
8000/8000 [==============================] - 1s 155us/step - loss: 0.3419 - accuracy: 0.8609
Epoch 8/50
8000/8000 [==============================] - 1s 152us/step - loss: 0.3393 - accuracy: 0.8630
Epoch 9/50
8000/8000 [==============================] - 1s 164us/step - l

In [38]:
score = classifier.evaluate(X_train, y_train, verbose=0)
print("%s: %.2f%%" % (classifier.metrics_names[1], score[1]*100))

accuracy: 90.18%


In [39]:
score = classifier.evaluate(X_test, y_test, verbose=0)
print("%s: %.2f%%" % (classifier.metrics_names[1], score[1]*100))

accuracy: 85.25%


In [40]:
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 10)

# Part 3 - Making the predictions and evaluating the model

Epoch 1/10
8000/8000 [==============================] - 2s 288us/step - loss: 0.5056 - accuracy: 0.7950
Epoch 2/10
8000/8000 [==============================] - 2s 247us/step - loss: 0.4250 - accuracy: 0.7960
Epoch 3/10
8000/8000 [==============================] - 2s 245us/step - loss: 0.4164 - accuracy: 0.7960
Epoch 4/10
8000/8000 [==============================] - 2s 241us/step - loss: 0.4079 - accuracy: 0.8126
Epoch 5/10
8000/8000 [==============================] - 2s 246us/step - loss: 0.3996 - accuracy: 0.8270
Epoch 6/10
8000/8000 [==============================] - 2s 241us/step - loss: 0.3930 - accuracy: 0.8280
Epoch 7/10
8000/8000 [==============================] - 2s 246us/step - loss: 0.3871 - accuracy: 0.8288
Epoch 8/10
8000/8000 [==============================] - 2s 241us/step - loss: 0.3821 - accuracy: 0.8375
Epoch 9/10
8000/8000 [==============================] - 2s 242us/step - loss: 0.3771 - accuracy: 0.8422
Epoch 10/10
8000/8000 [==============================] - 2s 247u

In [9]:
score = classifier.evaluate(X_train, y_train, verbose=0)
print("%s: %.2f%%" % (classifier.metrics_names[1], score[1]*100))

accuracy: 90.69%


In [10]:
score = classifier.evaluate(X_test, y_test, verbose=0)
print("%s: %.2f%%" % (classifier.metrics_names[1], score[1]*100))

accuracy: 84.85%


In [11]:
test_predictions = classifier.predict_classes(X_test)
y_test = y_test.reshape([2000, 1])

In [12]:
for i in range(2000):
    if test_predictions[i] != y_test[i]:
        print(test_predictions[i], y_test[i],'--!', i)
    else:
        print(test_predictions[i], y_test[i])

[0] [0]
[0] [1] --! 1
[0] [0]
[0] [0]
[0] [0]
[1] [1]
[0] [0]
[0] [0]
[0] [1] --! 8
[1] [1]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[1] [1]
[0] [1] --! 15
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[1] [0] --! 20
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [1] --! 31
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [1] --! 41
[0] [1] --! 42
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[1] [1]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [1] --! 58
[0] [1] --! 59
[0] [0]
[0] [0]
[0] [0]
[0] [1] --! 63
[0] [1] --! 64
[1] [1]
[0] [0]
[0] [0]
[0] [0]
[1] [1]
[1] [0] --! 70
[0] [0]
[0] [0]
[1] [1]
[1] [1]
[0] [0]
[1] [1]
[0] [0]
[0] [0]
[0] [0]
[1] [1]
[0] [1] --! 81
[0] [0]
[0] [0]
[0] [1] --! 84
[0] [0]
[0] [0]
[0] [0]
[1] [1]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[1] [1]
[0] [0]
[0] [1] --! 95
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [1] --! 107
[1] [0] --! 108
[0] [0]
[

[0] [0]
[0] [1] --! 949
[1] [0] --! 950
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [1] --! 956
[1] [1]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [1] --! 969
[1] [1]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [1] --! 976
[0] [0]
[0] [1] --! 978
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[1] [0] --! 985
[0] [1] --! 986
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [1] --! 996
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[1] [1]
[0] [0]
[0] [0]
[1] [1]
[0] [0]
[0] [1] --! 1006
[0] [0]
[0] [0]
[1] [1]
[0] [0]
[0] [0]
[0] [0]
[0] [1] --! 1013
[0] [0]
[0] [0]
[0] [1] --! 1016
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[1] [1]
[0] [0]
[1] [1]
[0] [0]
[1] [0] --! 1025
[0] [0]
[1] [0] --! 1027
[0] [0]
[0] [0]
[0] [0]
[1] [0] --! 1031
[0] [1] --! 1032
[0] [0]
[0] [0]
[1] [1]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[1] [1]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[0] [0]
[

In [15]:
import os
os.system("git add ")

0